const questions = [
    "If you’d get 10.000€, how would you spend them?",
    "How would you rate yourself on a scale from 1-10?",
    "Would you like to be famous, in what way?",
    "What would a ‘perfect’ day look like to you?",
    "Do you have a secret hunch about how you will die?",
    "Name three things, you believe the two of us have in common.",
    "For what in your life do you feel most grateful?",
    "If you could change anything about the way you were raised, what would it be?",
    "If you could wake up tomorrow having gained one skill to perfection, what would it be?",
    "If a crystal ball could tell you the truth about yourself, your life, the future or anything else, what would you want to know?",
    "What do you value most in a friendship?",
    "What is your most cherished memory?",
    "What is your most terrible memory?",
    "What’s your love language? (Physical Touch, Words of Affirmation, Quality Time, Acts of Service, Receiving Gifts)",
    "Name three things you like about your partner.",
    "What charity or social issue is most important to you? Why?",
    "What is your favorite outfit or item I wear?",
    "What’s your worst habit?",
    "How have you changed in the past five years?",
    "Tell a story of how a stranger changed your life.",
    "What did you want to be when you grew up?",
    "What’s the most embarrassing that has happened to you?",
    "Describe your ideal morning routine.",
    "What were you like as a student?",
    "What do you like to do when you have alone time?",
    "What’s something you wish I would do more of?",
    "If there was one thing you could tell your younger self, what would that be?",
    "What's a lesson you learned the hard way?",
    "Describe your date using only three words.",
    "What calms you down when you are stressed or upset?",
    "What does your dream house look like? Where is it?",
    "What was your first impression of me? Digital and in real life.",
    "What has been the best part of your day so far?",
    "Are you more like one of your parents? Which one?",
    "Describe yourself in three words.",
    "Both write down your three most important values in life. Compare.",
    "How do you define success?",
    "Is there something you’ve dreamed of doing? What’s kept you from doing it?",
    "What’s your biggest fear?",
    "What is your favorite feature about yourself?",
    "Is there anyone you look up to?",
    "Do you have any goals you’d like to accomplish this year?",
    "What’s something I introduced you to that you now like?",
    "What’s something you look forward to every day?",
    "Where is your favorite place to visit together?",
    "What’s been the best thing in your life to happen so far?",
    "What can a person do to make you unattracted to them, no matter how attractive they are?",
    "What’s something you wish you were really good at?",
    "What’s the most thrilling thing you’ve ever done?",
    "What’s something you love about your hometown?",
    "Describe why you're thankful for the person you're answering these questions with.",
    "Is there a song that immediately lifts your mood? Which one?",
    "Where is the most beautiful place you have ever been?"
];

export default questions;
